name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Time
        run: import datetime; now = datetime.datetime.now(); print(now.time())
